import os
class Config:
    FLASK_SECRET = os.getenv("FLASK_SECRET", "changeme")
    AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN", "")
    AUTH0_AUDIENCE = os.getenv("AUTH0_AUDIENCE", "https://surveilens/api")
    AUTH0_SPA_DOMAIN = os.getenv("AUTH0_SPA_DOMAIN", "")
    AUTH0_SPA_CLIENT_ID = os.getenv("AUTH0_SPA_CLIENT_ID", "")
    AUTH0_M2M_CLIENT_ID = os.getenv("AUTH0_M2M_CLIENT_ID", "")
    AUTH0_M2M_CLIENT_SECRET = os.getenv("AUTH0_M2M_CLIENT_SECRET", "")
    REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
    NEURALSEEK_URL = os.getenv("NEURALSEEK_URL", "")
    NEURALSEEK_KEY = os.getenv("NEURALSEEK_KEY", "")
    GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    DEMO_MODE = os.getenv("DEMO_MODE", "true").lower() == "true"
    SITE_ID = os.getenv("SITE_ID", "site-01")
    SNOW_ACCOUNT = os.getenv("SNOW_ACCOUNT")
    SNOW_USER = os.getenv("SNOW_USER")
    SNOW_PASS = os.getenv("SNOW_PASS")
    SNOW_WH = os.getenv("SNOW_WH", "COMPUTE_WH")
    SNOW_DB = os.getenv("SNOW_DB", "SURVEILENS")
    SNOW_SCHEMA = os.getenv("SNOW_SCHEMA", "CORE")
    VULTR_ENDPOINT = os.getenv("VULTR_OBJECTS_ENDPOINT")
    VULTR_BUCKET = os.getenv("VULTR_OBJECTS_BUCKET")
    VULTR_KEY = os.getenv("VULTR_OBJECTS_KEY")
    VULTR_SECRET = os.getenv("VULTR_OBJECTS_SECRET")
    SOLANA_RPC = os.getenv("SOLANA_RPC", "https://api.devnet.solana.com")
    SOLANA_SIGNER_PRIVATE_KEY = os.getenv("SOLANA_SIGNER_PRIVATE_KEY", "")
    ELEVEN_API_KEY = os.getenv("ELEVEN_API_KEY", "")
    ELEVEN_VOICE_ID = os.getenv("ELEVEN_VOICE_ID", "")
